//compile with: protoc -I ./pkg/api/nadzornaRavnina  --go_out=paths=source_relative:./pkg/api/nadzornaRavnina  --go-grpc_out=paths=source_relative:./pkg/api/nadzornaRavnina  pkg/api/nadzornaRavnina/nadzornaRavnina.proto

syntax = "proto3";

package controlplane;

option go_package = "pkg/api/nadzorna_ravnina";

import "google/protobuf/empty.proto"; 

// Node information
message NodeInfo {
    string node_id = 1;
    string address = 2;
}

// Response for GetClusterState
message GetClusterStateResponse {
    NodeInfo head = 1;
    NodeInfo tail = 2;
}

// Request message for registering a node
message RegisterNodeRequest {
  string node_id = 1;
  string address = 2;
}

// Response message for registering a node
message RegisterNodeResponse {
  bool success = 1;
  string message = 2;
  bool is_head = 3;
  bool is_tail = 4;
}

message SubscriptionNodeRequest {
  int64 user_id = 1;
  repeated int64 topic_id = 2;
}

message SubscriptionNodeResponse {
  string subscribe_token = 1; // subscription token to be presented to the returned node
  NodeInfo node = 2;
}

message HeartbeatRequest {
  string node_id = 1;
}

message SubscribeToChangesRequest {
  string node_id = 1;
}

message Changes {
  string next_adress = 1;
}

// ControlPlane service
service ControlPlane {
    // Client: Returns current head and tail of the cluster
    rpc GetClusterState(google.protobuf.Empty) returns (GetClusterStateResponse);
    // Server: Register a new node
    rpc RegisterNode(RegisterNodeRequest) returns (RegisterNodeResponse);
    // Client: Request a node to which a subscription can be opened.
    rpc GetSubscriptionNode(SubscriptionNodeRequest) returns (SubscriptionNodeResponse);
    // Server: Check if servers are alive or down
    rpc Heartbeat(HeartbeatRequest) returns (google.protobuf.Empty);
    // Server:
    rpc SubscribeToChanges(SubscribeToChangesRequest) returns (stream Changes);
}
