//compile with: protoc -I ./pkg/api/nadzornaRavnina  --go_out=paths=source_relative:./pkg/api/nadzornaRavnina  --go-grpc_out=paths=source_relative:./pkg/api/nadzornaRavnina  pkg/api/nadzornaRavnina/nadzornaRavnina.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: nadzornaRavnina.proto

package nadzorna_ravnina

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Node information
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_nadzornaRavnina_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nadzornaRavnina_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_nadzornaRavnina_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// Response for GetClusterState
type GetClusterStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Head          *NodeInfo              `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Tail          *NodeInfo              `protobuf:"bytes,2,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterStateResponse) Reset() {
	*x = GetClusterStateResponse{}
	mi := &file_nadzornaRavnina_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStateResponse) ProtoMessage() {}

func (x *GetClusterStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nadzornaRavnina_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStateResponse.ProtoReflect.Descriptor instead.
func (*GetClusterStateResponse) Descriptor() ([]byte, []int) {
	return file_nadzornaRavnina_proto_rawDescGZIP(), []int{1}
}

func (x *GetClusterStateResponse) GetHead() *NodeInfo {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *GetClusterStateResponse) GetTail() *NodeInfo {
	if x != nil {
		return x.Tail
	}
	return nil
}

// Request message for registering a node
type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_nadzornaRavnina_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nadzornaRavnina_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_nadzornaRavnina_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// Response message for registering a node
type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	IsHead        bool                   `protobuf:"varint,3,opt,name=is_head,json=isHead,proto3" json:"is_head,omitempty"`
	IsTail        bool                   `protobuf:"varint,4,opt,name=is_tail,json=isTail,proto3" json:"is_tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_nadzornaRavnina_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nadzornaRavnina_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_nadzornaRavnina_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterNodeResponse) GetIsHead() bool {
	if x != nil {
		return x.IsHead
	}
	return false
}

func (x *RegisterNodeResponse) GetIsTail() bool {
	if x != nil {
		return x.IsTail
	}
	return false
}

type SubscriptionNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TopicId       []int64                `protobuf:"varint,2,rep,packed,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionNodeRequest) Reset() {
	*x = SubscriptionNodeRequest{}
	mi := &file_nadzornaRavnina_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionNodeRequest) ProtoMessage() {}

func (x *SubscriptionNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nadzornaRavnina_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionNodeRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionNodeRequest) Descriptor() ([]byte, []int) {
	return file_nadzornaRavnina_proto_rawDescGZIP(), []int{4}
}

func (x *SubscriptionNodeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscriptionNodeRequest) GetTopicId() []int64 {
	if x != nil {
		return x.TopicId
	}
	return nil
}

type SubscriptionNodeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscribeToken string                 `protobuf:"bytes,1,opt,name=subscribe_token,json=subscribeToken,proto3" json:"subscribe_token,omitempty"` // subscription token to be presented to the returned node
	Node           *NodeInfo              `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscriptionNodeResponse) Reset() {
	*x = SubscriptionNodeResponse{}
	mi := &file_nadzornaRavnina_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionNodeResponse) ProtoMessage() {}

func (x *SubscriptionNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nadzornaRavnina_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionNodeResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionNodeResponse) Descriptor() ([]byte, []int) {
	return file_nadzornaRavnina_proto_rawDescGZIP(), []int{5}
}

func (x *SubscriptionNodeResponse) GetSubscribeToken() string {
	if x != nil {
		return x.SubscribeToken
	}
	return ""
}

func (x *SubscriptionNodeResponse) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_nadzornaRavnina_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nadzornaRavnina_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_nadzornaRavnina_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type SubscribeToChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeToChangesRequest) Reset() {
	*x = SubscribeToChangesRequest{}
	mi := &file_nadzornaRavnina_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToChangesRequest) ProtoMessage() {}

func (x *SubscribeToChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nadzornaRavnina_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToChangesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeToChangesRequest) Descriptor() ([]byte, []int) {
	return file_nadzornaRavnina_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeToChangesRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type Changes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextAdress    string                 `protobuf:"bytes,1,opt,name=next_adress,json=nextAdress,proto3" json:"next_adress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Changes) Reset() {
	*x = Changes{}
	mi := &file_nadzornaRavnina_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Changes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Changes) ProtoMessage() {}

func (x *Changes) ProtoReflect() protoreflect.Message {
	mi := &file_nadzornaRavnina_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Changes.ProtoReflect.Descriptor instead.
func (*Changes) Descriptor() ([]byte, []int) {
	return file_nadzornaRavnina_proto_rawDescGZIP(), []int{8}
}

func (x *Changes) GetNextAdress() string {
	if x != nil {
		return x.NextAdress
	}
	return ""
}

var File_nadzornaRavnina_proto protoreflect.FileDescriptor

const file_nadzornaRavnina_proto_rawDesc = "" +
	"\n" +
	"\x15nadzornaRavnina.proto\x12\fcontrolplane\x1a\x1bgoogle/protobuf/empty.proto\"=\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"q\n" +
	"\x17GetClusterStateResponse\x12*\n" +
	"\x04head\x18\x01 \x01(\v2\x16.controlplane.NodeInfoR\x04head\x12*\n" +
	"\x04tail\x18\x02 \x01(\v2\x16.controlplane.NodeInfoR\x04tail\"H\n" +
	"\x13RegisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"|\n" +
	"\x14RegisterNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\ais_head\x18\x03 \x01(\bR\x06isHead\x12\x17\n" +
	"\ais_tail\x18\x04 \x01(\bR\x06isTail\"M\n" +
	"\x17SubscriptionNodeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\btopic_id\x18\x02 \x03(\x03R\atopicId\"o\n" +
	"\x18SubscriptionNodeResponse\x12'\n" +
	"\x0fsubscribe_token\x18\x01 \x01(\tR\x0esubscribeToken\x12*\n" +
	"\x04node\x18\x02 \x01(\v2\x16.controlplane.NodeInfoR\x04node\"+\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"4\n" +
	"\x19SubscribeToChangesRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"*\n" +
	"\aChanges\x12\x1f\n" +
	"\vnext_adress\x18\x01 \x01(\tR\n" +
	"nextAdress2\xa9\x03\n" +
	"\fControlPlane\x12P\n" +
	"\x0fGetClusterState\x12\x16.google.protobuf.Empty\x1a%.controlplane.GetClusterStateResponse\x12U\n" +
	"\fRegisterNode\x12!.controlplane.RegisterNodeRequest\x1a\".controlplane.RegisterNodeResponse\x12d\n" +
	"\x13GetSubscriptionNode\x12%.controlplane.SubscriptionNodeRequest\x1a&.controlplane.SubscriptionNodeResponse\x12C\n" +
	"\tHeartbeat\x12\x1e.controlplane.HeartbeatRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\x12SubscribeToChanges\x12\x16.google.protobuf.Empty\x1a\x15.controlplane.Changes0\x01B\x1aZ\x18pkg/api/nadzorna_ravninab\x06proto3"

var (
	file_nadzornaRavnina_proto_rawDescOnce sync.Once
	file_nadzornaRavnina_proto_rawDescData []byte
)

func file_nadzornaRavnina_proto_rawDescGZIP() []byte {
	file_nadzornaRavnina_proto_rawDescOnce.Do(func() {
		file_nadzornaRavnina_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nadzornaRavnina_proto_rawDesc), len(file_nadzornaRavnina_proto_rawDesc)))
	})
	return file_nadzornaRavnina_proto_rawDescData
}

var file_nadzornaRavnina_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_nadzornaRavnina_proto_goTypes = []any{
	(*NodeInfo)(nil),                  // 0: controlplane.NodeInfo
	(*GetClusterStateResponse)(nil),   // 1: controlplane.GetClusterStateResponse
	(*RegisterNodeRequest)(nil),       // 2: controlplane.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),      // 3: controlplane.RegisterNodeResponse
	(*SubscriptionNodeRequest)(nil),   // 4: controlplane.SubscriptionNodeRequest
	(*SubscriptionNodeResponse)(nil),  // 5: controlplane.SubscriptionNodeResponse
	(*HeartbeatRequest)(nil),          // 6: controlplane.HeartbeatRequest
	(*SubscribeToChangesRequest)(nil), // 7: controlplane.SubscribeToChangesRequest
	(*Changes)(nil),                   // 8: controlplane.Changes
	(*emptypb.Empty)(nil),             // 9: google.protobuf.Empty
}
var file_nadzornaRavnina_proto_depIdxs = []int32{
	0, // 0: controlplane.GetClusterStateResponse.head:type_name -> controlplane.NodeInfo
	0, // 1: controlplane.GetClusterStateResponse.tail:type_name -> controlplane.NodeInfo
	0, // 2: controlplane.SubscriptionNodeResponse.node:type_name -> controlplane.NodeInfo
	9, // 3: controlplane.ControlPlane.GetClusterState:input_type -> google.protobuf.Empty
	2, // 4: controlplane.ControlPlane.RegisterNode:input_type -> controlplane.RegisterNodeRequest
	4, // 5: controlplane.ControlPlane.GetSubscriptionNode:input_type -> controlplane.SubscriptionNodeRequest
	6, // 6: controlplane.ControlPlane.Heartbeat:input_type -> controlplane.HeartbeatRequest
	9, // 7: controlplane.ControlPlane.SubscribeToChanges:input_type -> google.protobuf.Empty
	1, // 8: controlplane.ControlPlane.GetClusterState:output_type -> controlplane.GetClusterStateResponse
	3, // 9: controlplane.ControlPlane.RegisterNode:output_type -> controlplane.RegisterNodeResponse
	5, // 10: controlplane.ControlPlane.GetSubscriptionNode:output_type -> controlplane.SubscriptionNodeResponse
	9, // 11: controlplane.ControlPlane.Heartbeat:output_type -> google.protobuf.Empty
	8, // 12: controlplane.ControlPlane.SubscribeToChanges:output_type -> controlplane.Changes
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_nadzornaRavnina_proto_init() }
func file_nadzornaRavnina_proto_init() {
	if File_nadzornaRavnina_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nadzornaRavnina_proto_rawDesc), len(file_nadzornaRavnina_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nadzornaRavnina_proto_goTypes,
		DependencyIndexes: file_nadzornaRavnina_proto_depIdxs,
		MessageInfos:      file_nadzornaRavnina_proto_msgTypes,
	}.Build()
	File_nadzornaRavnina_proto = out.File
	file_nadzornaRavnina_proto_goTypes = nil
	file_nadzornaRavnina_proto_depIdxs = nil
}
