//compile with: protoc --proto_path=pkg/api/nadzornaRavnina --go_out=pkg/api/nadzornaRavnina --go-grpc_out=pkg/api/nadzornaRavnina pkg/api/nadzornaRavnina/nadzornaRavnina.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: nadzornaRavnina.proto

package nadzorna_ravnina

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Node information
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_nadzornaRavnina_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nadzornaRavnina_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_nadzornaRavnina_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// Response for GetClusterState
type GetClusterStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Head          *NodeInfo              `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Tail          *NodeInfo              `protobuf:"bytes,2,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterStateResponse) Reset() {
	*x = GetClusterStateResponse{}
	mi := &file_nadzornaRavnina_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStateResponse) ProtoMessage() {}

func (x *GetClusterStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nadzornaRavnina_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStateResponse.ProtoReflect.Descriptor instead.
func (*GetClusterStateResponse) Descriptor() ([]byte, []int) {
	return file_nadzornaRavnina_proto_rawDescGZIP(), []int{1}
}

func (x *GetClusterStateResponse) GetHead() *NodeInfo {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *GetClusterStateResponse) GetTail() *NodeInfo {
	if x != nil {
		return x.Tail
	}
	return nil
}

var File_nadzornaRavnina_proto protoreflect.FileDescriptor

const file_nadzornaRavnina_proto_rawDesc = "" +
	"\n" +
	"\x15nadzornaRavnina.proto\x12\fcontrolplane\x1a\x1bgoogle/protobuf/empty.proto\"=\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"q\n" +
	"\x17GetClusterStateResponse\x12*\n" +
	"\x04head\x18\x01 \x01(\v2\x16.controlplane.NodeInfoR\x04head\x12*\n" +
	"\x04tail\x18\x02 \x01(\v2\x16.controlplane.NodeInfoR\x04tail2`\n" +
	"\fControlPlane\x12P\n" +
	"\x0fGetClusterState\x12\x16.google.protobuf.Empty\x1a%.controlplane.GetClusterStateResponseB\x1aZ\x18pkg/api/nadzorna_ravninab\x06proto3"

var (
	file_nadzornaRavnina_proto_rawDescOnce sync.Once
	file_nadzornaRavnina_proto_rawDescData []byte
)

func file_nadzornaRavnina_proto_rawDescGZIP() []byte {
	file_nadzornaRavnina_proto_rawDescOnce.Do(func() {
		file_nadzornaRavnina_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nadzornaRavnina_proto_rawDesc), len(file_nadzornaRavnina_proto_rawDesc)))
	})
	return file_nadzornaRavnina_proto_rawDescData
}

var file_nadzornaRavnina_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nadzornaRavnina_proto_goTypes = []any{
	(*NodeInfo)(nil),                // 0: controlplane.NodeInfo
	(*GetClusterStateResponse)(nil), // 1: controlplane.GetClusterStateResponse
	(*emptypb.Empty)(nil),           // 2: google.protobuf.Empty
}
var file_nadzornaRavnina_proto_depIdxs = []int32{
	0, // 0: controlplane.GetClusterStateResponse.head:type_name -> controlplane.NodeInfo
	0, // 1: controlplane.GetClusterStateResponse.tail:type_name -> controlplane.NodeInfo
	2, // 2: controlplane.ControlPlane.GetClusterState:input_type -> google.protobuf.Empty
	1, // 3: controlplane.ControlPlane.GetClusterState:output_type -> controlplane.GetClusterStateResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nadzornaRavnina_proto_init() }
func file_nadzornaRavnina_proto_init() {
	if File_nadzornaRavnina_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nadzornaRavnina_proto_rawDesc), len(file_nadzornaRavnina_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nadzornaRavnina_proto_goTypes,
		DependencyIndexes: file_nadzornaRavnina_proto_depIdxs,
		MessageInfos:      file_nadzornaRavnina_proto_msgTypes,
	}.Build()
	File_nadzornaRavnina_proto = out.File
	file_nadzornaRavnina_proto_goTypes = nil
	file_nadzornaRavnina_proto_depIdxs = nil
}
